<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor HP atau Email_email-phone</name>
   <tag></tag>
   <elementGuidId>efe74f97-af4f-4aff-affe-285d10404713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d91522a-535b-4a88-b8e3-06eba49c457b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>edb07953-16d6-47a9-a19f-3f0f68d74907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>25e4f152-a471-46e5-bcd0-7cd6b2522a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-phone</value>
      <webElementGuid>506ac6bb-c507-4a3e-9598-e010bded89d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>55dc4710-633b-468f-be0d-a97bdb3f0d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>email-phone-input</value>
      <webElementGuid>62392d20-f2e1-444d-ac69-4f17e9b32d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wc186l e110g5pc0</value>
      <webElementGuid>1aa6f7e7-0a20-48ac-889f-9bd08e4198a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>f7aa06bd-5adc-4230-a818-bda90166da5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-phone&quot;)</value>
      <webElementGuid>76832502-8b43-40de-b497-69ff84bd86fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-phone']</value>
      <webElementGuid>e9c80886-cfff-4efd-99b3-dcf583d61425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>bd884b80-6b74-4b2b-bbb1-535fb1f1efb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email-phone' and @type = 'email']</value>
      <webElementGuid>08e332c6-92ee-44fa-9e8f-a0b452dac7fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
