<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6550db77-bf02-46c7-b402-62c495a27099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homepage-home-section-app']/section/div/div/div/div/div/div/div[3]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>39000334-d638-4d6a-96b3-eb2e750637ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s2.bukalapak.com/dope/1581555601589/original/hp_menu_icon_f28ec829-40fd-4dbd-9ef3-7d491cfc3e5a.jpg</value>
      <webElementGuid>f18e2303-396f-4bf6-acdc-66f636277926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bukalapak</value>
      <webElementGuid>8d93a181-d608-4f3b-b41b-a04b70319b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homepage-home-section-app&quot;)/section[@class=&quot;bl-section dope-section mt-48&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;qa-dope-container bl-dope-container&quot;]/div[@class=&quot;bl-dope-container__wrapper&quot;]/div[@class=&quot;bl-dope-container__head&quot;]/div[@class=&quot;bl-dope-container__head-content&quot;]/div[@class=&quot;bl-flex-container mb-0 bl-dope-container__grid-wrapper&quot;]/div[@class=&quot;bl-flex-item mt-16 mb-16 bl-dope-container__grid-item&quot;]/a[@class=&quot;bl-dope-item bl-dope-item--medium&quot;]/div[@class=&quot;bl-dope-item__body&quot;]/img[1]</value>
      <webElementGuid>b9c4aad0-28b7-4555-80f8-2834b398d622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homepage-home-section-app']/section/div/div/div/div/div/div/div[3]/a/div/img</value>
      <webElementGuid>8727b8c0-479d-4668-98a5-987327596d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Bukalapak'])[3]</value>
      <webElementGuid>4e785fc4-cbc2-4d62-9d21-072b0b7545d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/img</value>
      <webElementGuid>3e364e24-2a2a-438b-a270-ffb8b478662d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s2.bukalapak.com/dope/1581555601589/original/hp_menu_icon_f28ec829-40fd-4dbd-9ef3-7d491cfc3e5a.jpg' and @alt = 'Bukalapak']</value>
      <webElementGuid>3ba866ee-1559-4287-8a2f-57de16265c8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
