<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_css-1wc186l e110g5pc0</name>
   <tag></tag>
   <elementGuidId>7484fa5c-e88e-4bcf-a25c-68df0f161681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.css-1wc186l.e110g5pc0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5b8103a-1623-4737-b7c0-524243a8f059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e86cc185-4fef-4926-9a3b-01200bffb716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cari jam tangan pria</value>
      <webElementGuid>c99d1fcd-2b5b-4e9e-9872-73031e5eab7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>702d39cd-452f-40b9-a1b6-dd780bf40aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari jam tangan pria</value>
      <webElementGuid>6f34b940-7507-4695-b55a-a26bb4945114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wc186l e110g5pc0</value>
      <webElementGuid>4cf2209f-0f17-490a-80dc-460696ea628d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-main-wrapper&quot;)/div[@class=&quot;css-1s8dqy5 e90swyx2&quot;]/div[@class=&quot;css-1a6ytj8&quot;]/div[@class=&quot;css-w3ze74&quot;]/div[@class=&quot;css-1aeefbt&quot;]/div[@class=&quot;css-1y5dsat&quot;]/div[@class=&quot;css-xqly7f e1v32nag0&quot;]/input[@class=&quot;css-1wc186l e110g5pc0&quot;]</value>
      <webElementGuid>7a761d34-eb57-4f76-b57d-106bcdc386c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>09fe1bcd-ee04-439d-a804-c74c7a2fa631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-main-wrapper']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>341544fd-e433-4b1c-af16-2033462ce2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>82821f8b-68be-4e6f-a629-3d59fc5c64e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Cari jam tangan pria']</value>
      <webElementGuid>9f10d13f-d44c-435e-a5c1-a940c0626a2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
