<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rizki</name>
   <tag></tag>
   <elementGuidId>255ce905-af5a-45d7-890a-376faf24e225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-profile-header']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#my-profile-header > div.css-lipffl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc88042a-19a8-44f2-a232-05026a4d95c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-lipffl</value>
      <webElementGuid>d3b184dd-e5bb-4d6d-a30a-c4a05efb4c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rizki</value>
      <webElementGuid>8271b824-57df-4bcd-8f0e-0b0d6e9d70ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-profile-header&quot;)/div[@class=&quot;css-lipffl&quot;]</value>
      <webElementGuid>fc6878d0-d2fc-40c1-8a8b-047377672a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-profile-header']/div</value>
      <webElementGuid>0bc34318-22e4-4dd8-a7de-25d119d27db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[2]</value>
      <webElementGuid>89209d31-0288-4b20-9664-f3f88db7f531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::div[18]</value>
      <webElementGuid>cca01589-890f-4070-9a2a-9266b3aedb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizki'])[2]/preceding::div[3]</value>
      <webElementGuid>3bb66a82-6f76-4a2d-be54-aa61995938e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div</value>
      <webElementGuid>ce6aa53f-9473-4914-b60e-b89d90419ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rizki' or . = 'Rizki')]</value>
      <webElementGuid>88480410-8dfe-412a-b4ed-c46f0165644e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
