<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>98e54e6e-05ee-4a01-9793-7820b18f4e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homepage-home-section-app']/section/div/div/div/div/div/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Bukalapak&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e03068e8-7b0b-4c43-8b0d-69c54dfba6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s4.bukalapak.com/athena/1606361301726/original/hp_menu_icon_6ff40e16-7e1b-4fb2-881f-0ac9c4cc1113.jpg</value>
      <webElementGuid>cd853288-bc1c-42a0-b345-6460e49810ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bukalapak</value>
      <webElementGuid>95051154-a5ce-4745-bf0d-0bfbe867c82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homepage-home-section-app&quot;)/section[@class=&quot;bl-section dope-section mt-48&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;qa-dope-container bl-dope-container&quot;]/div[@class=&quot;bl-dope-container__wrapper&quot;]/div[@class=&quot;bl-dope-container__head&quot;]/div[@class=&quot;bl-dope-container__head-content&quot;]/div[@class=&quot;bl-flex-container mb-0 bl-dope-container__grid-wrapper&quot;]/div[@class=&quot;bl-flex-item mt-16 mb-16 bl-dope-container__grid-item&quot;]/a[@class=&quot;bl-dope-item bl-dope-item--medium&quot;]/div[@class=&quot;bl-dope-item__body&quot;]/img[1]</value>
      <webElementGuid>91fb7389-da35-4012-956b-bd51b860fa2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homepage-home-section-app']/section/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>1a810294-4423-452c-bb8c-ff99a1b394b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bukalapak']</value>
      <webElementGuid>e428a1fc-8e86-4220-96db-eb408c404aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>ba3cf051-0619-4acd-863c-f32d025022a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s4.bukalapak.com/athena/1606361301726/original/hp_menu_icon_6ff40e16-7e1b-4fb2-881f-0ac9c4cc1113.jpg' and @alt = 'Bukalapak']</value>
      <webElementGuid>66ce4b22-55a7-48df-bdf2-659fd401fbc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
